# Generated by Django 5.2 on 2026-01-13 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=50)),
                ('product_url', models.URLField(max_length=500)),
                ('skin_concern', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkinAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='skin_scans/original/%Y/%m/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='skin_scans/processed/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_type', models.CharField(default='unknown', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('acne_data', models.JSONField(default=list)),
                ('wrinkles_data', models.JSONField(default=list)),
                ('eyebags_data', models.JSONField(default=list)),
                ('eczema_data', models.JSONField(default=list)),
                ('acne_count', models.IntegerField(default=0)),
                ('wrinkle_score', models.FloatField(default=0.0)),
                ('eyebag_score', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='core.skinanalysis')),
            ],
        ),
    ]
