# Generated by Django 5.2 on 2026-01-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('skin_tone', models.CharField(max_length=50)),
                ('skin_type', models.CharField(max_length=50)),
                ('assessment_frequency', models.CharField(max_length=50)),
                ('prior_method', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
    ]
