# Generated by Django 5.1.7 on 2025-04-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_image_uploaded_at_alter_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='uploaded_at',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='image',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='request_type',
            field=models.CharField(default='unknown', max_length=10),
        ),
    ]
