# Generated by Django 5.1.7 on 2025-04-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_uploaded_at_image_timestamp_image_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to='processed/'),
        ),
    ]
