# Generated by Django 5.2.1 on 2025-05-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('acne', models.JSONField()),
                ('wrinkles', models.JSONField()),
                ('eyebags', models.JSONField()),
            ],
        ),
    ]
