# Generated by Django 5.2.1 on 2025-05-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='eczema',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='progress',
            name='acne',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='progress',
            name='eyebags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='progress',
            name='wrinkles',
            field=models.JSONField(default=list),
        ),
    ]
