# Generated by Django 5.2.1 on 2025-07-02 18:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_userprofile_age_remove_userprofile_skin_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='progress',
            name='progress_plot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='Project_Folder/original/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to='Project_Folder/processed/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
